### PR TITLE
Better handling for NaN in betting lines

### LINKED ISSUE #93: cfbd_betting_lines
In cfbfastR_1.9.0 it only loads certain years of betting data, for example, 2019-2022 but not 2023.  However when cross-referenced with the cfbdata website, the betting data can be found there. I also attempted running the code while directly referencing the package (cfbfastR::), as per a previous closed bug report, but to no avail.

**To Reproduce**
1. bet_data <- cfbd_betting_lines(year = 2023)
2. also attempted: bet_i <- cfbfastR::cfbd_betting_lines(year = i)
3. Error: 2023-11-07 20:13:31: Invalid arguments or no betting lines data available!

**Expected behavior**
Should return my dataset named bet_data containing the betting lines data frame

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by akeaswaran**
Closes #93.

## Summary by CodeRabbit

- **Enhancements**
  - Improved data processing logic in the betting lines feature for more accurate and refined results.

### CODE REVIEW

File: R/cfbd_betting.R [hunk 1]
```diff
@@ -136,10 +137,27 @@ cfbd_betting_lines <- function(game_id = NULL,
       # Get the content and return it as data.frame
       df <- res %>%
         httr::content(as = "text", encoding = "UTF-8") %>%
+        stringr::str_replace_all("NaN", 'null') %>%
         jsonlite::fromJSON(flatten = TRUE) %>%
         purrr::map_if(is.data.frame, list) %>%
         dplyr::as_tibble() %>%
-        tidyr::unnest("lines")
+        tidyr::unnest("lines") %>%
+        dplyr::mutate(
```
Comment (saiemgilani) [inline R/cfbd_betting.R:145]: these need to be `.data$overUnder`, `.data$spread`, `.data$formattedSpread` on the RHS inside the `dplyr::case_when`. Please make these changes and it's approved.

**Review by saiemgilani — CHANGES_REQUESTED** [review]

**Review by saiemgilani — APPROVED** [review]

File: R/cfbd_betting.R (hunk 1 above)
Comment (saiemgilani) [reply R/cfbd_betting.R:145]: resolved by [60b1fb2](https://github.com/sportsdataverse/cfbfastR/pull/96/commits/60b1fb27e93ecab68fa01a433dc5fd33a9282c2e)
